### ISSUE TITLE
Is it possible to make work in 2D games?

### ISSUE THREAD

**Issue by BinarryCode** [headshot2017/libsm64-gm8#2]
Self explanatory (I am trying to modify default Mega Engine to add this)
also I tried this on a 8.1 modification (Game Maker 8.2) and it doesn't work

**Comment by headshot2017** [comment]
you can use orthographic projection to draw 3D models in a 2D view, you can see the example gmk project since it draws an FPS counter with orthographic projection

this is the first time i hear of Game Maker 8.2, so i'll have to look at it later and see if i can get the extension to work with it

**Comment by BinarryCode** [comment]
I tried that and it didnt seem to work too well (im assuming the collision array level.cpp isnt being updated or something?)
also I can dm an invite to the server, its not meant to be entirely public due to the way its currently setup

**Comment by headshot2017** [comment]
the collision data from level.cpp is only meant to be temporary since i needed a quick way to set up collisions and get mario's model drawn. at some point in the future i'll remove it and make functions to add/remove static surfaces within GM8

i also wouldn't mind getting an invite for the server to see what it's all about

**Comment by BinarryCode** [comment]
you can friend me on discord (`binarycode_`) so i can give you a server invite
